language: python
python:
- '3.9'
dist: xenial
install:
- python setup.py install
- python -m pip install .[dev]
script:
# - make -C docs doctest
- python setup.py test
env:
  global:
    - MIN_SCRAPING_DELAY=11